# https://hub.docker.com/r/library/postgres/tags/
services:
  - postgres:9.6.2-alpine

# https://hub.docker.com/r/library/node/tags/
image: node:6.11

variables:
  POSTGRES_DB: gmnst_test
  POSTGRES_USER: gmnst_tester
  POSTGRES_PASSWORD: ""
  DATABASE_URL: "postgres://postgres@postgres/gmnst_test"

stages:
  - test

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - npm run knex:migrate
  - npm run knex:seed

test_server:
  stage: test
  services:
    - postgres:9.6.2-alpine
  script:
  #  - node ./specs/start.js ./specs/async.spec.js
    - npm run test:server

# test_db:
#   stage: test
#   services:
#     - postgres:9.5.0
#   script:
#    - npm install
#    - node ./specs/start.js ./specs/db-postgres.spec.js
#   tags:
#     - docker

#test_db:
#  script:
#   - npm install
#   - node ./specs/start.js ./specs/db-postgres.spec.js
