language: node_js

dist: trusty

sudo: required

node_js:
  - "6"

install:
  - sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
  - nanobox evar add NODE_ENV=production
  - nanobox run npm install

before_script:
  - nanobox run npm run knex:migrate
  - nanobox run npm run knex:seed
  - nanobox run npm run build

script: nanobox run npm run test:server

after_success:
  - nanobox remote add gmnst-prod
  - nanobox deploy

notifications:
  email: false