language: node_js

sudo: false

node_js:
  - "6"

services:
  - postgresql

env:
  - NODE_ENV="development"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - npm install -g knex

install:
  - export NODE_ENV=development
  - npm install
  - knex migrate:latest
  - knex seed:run

# https://github.com/travis-ci/travis-ci/issues/4771
env:
  - CXX=g++-4.8

# https://github.com/travis-ci/travis-ci/issues/4771
addons:
  postgresql: "9.4"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

notifications:
  email: false