language: node_js

dist: trusty

sudo: required

node_js:
  - "6"

services:
  - postgresql

install:
  - sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
  - export NODE_ENV=development
  - npm install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - nanobox run npm run knex-migrate
  - nanobox run npm run knex-seed
  - nanobox run npm run build

script: nanobox run npm run test:server

after_success:
  - nanobox remote add gmnst-prod
  - nanobox deploy

# https://github.com/travis-ci/travis-ci/issues/4771
env:
  - CXX=g++-4.8

# https://github.com/travis-ci/travis-ci/issues/4771
addons:
  postgresql: "9.6"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

notifications:
  email: true