language: node_js
node_js:
  - "6"

services:
  - postgresql

env:
  - NODE_ENV="development"

before_script:
  - psql -c 'create database gmnst_test;' -U postgres

before_install:
  - npm install knex

install:
  - export NODE_ENV=development
  - npm install
  - knex migrate:latest
  - knex seed:run

