language: node_js

dist: trusty

sudo: required

node_js:
  - "6"

install:
  - sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
  - nanobox evar add NODE_ENV=production
  - nanobox run npm install
  - nanobox evar add local DATA_DB_NAME=$DATA_DB_NAME
  - nanobox evar add local ADMIN_EMAIL=$ADMIN_EMAIL
  - nanobox evar add local BRAINTREE_ENVIRONMENT=$BRAINTREE_ENVIRONMENT
  - nanobox evar add local BRAINTREE_MERCHANT_ID=$BRAINTREE_MERCHANT_ID
  - nanobox evar add local BRAINTREE_PRIVATE_KEY=$BRAINTREE_PRIVATE_KEY 
  - nanobox evar add local BRAINTREE_PUBLIC_KEY=$BRAINTREE_PUBLIC_KEY
  - nanobox evar add local CART_TOKEN_SECRET=$CART_TOKEN_SECRET
  - nanobox evar add local EMAIL_FROM_CART_SUCCESS=$EMAIL_FROM_CART_SUCCESS
  - nanobox evar add local EMAIL_FROM_CART_SUCCESS_NAME=$EMAIL_FROM_CART_SUCCESS_NAME
  - nanobox evar add local JWT_CLIENT_ID=$JWT_CLIENT_ID
  - nanobox evar add local JWT_SERVER_SECRET=$JWT_SERVER_SECRET
  - nanobox evar add local MAILGUN_API_KEY=$MAILGUN_API_KEY
  - nanobox evar add local MAILGUN_DOMAIN=$MAILGUN_DOMAIN
  - nanobox evar add local MAILGUN_DOMAIN_PROD=$MAILGUN_DOMAIN_PROD
  - nanobox evar add local SHIPENGINE_API_KEY_PROD=$SHIPENGINE_API_KEY_PROD
  - nanobox evar add local SHIPENGINE_CARRIER_ID_FEDEX=$SHIPENGINE_CARRIER_ID_FEDEX
  - nanobox evar add local SHIPPING_FLAT_COST=$SHIPPING_FLAT_COST
  - nanobox evar add local TAX_RATE_CALIFORNIA=$TAX_RATE_CALIFORNIA
  - echo "====== Environment variables ======"
  - nanobox evar ls local
  - nanobox run npm run build
  - nanobox run npm run knex:migrate
  - nanobox run npm run knex:seed

script: nanobox run npm run test:server

after_success:
  - nanobox remote add gmnst-prod
  - nanobox deploy

notifications:
  email:
    recipients:
      - gregbruins@gmail.com
    # always|never|change - change is when the repo status goes from pass to fail or vice versa
    on_success: always
    on_failure: always