language: node_js
node_js:
  - "6"

services:
  - postgresql

#packages:

env:
  - NODE_ENV="development"

before_script:
  - psql -c 'create database gmnst_test;' -U postgres

before_install:
  - npm install knex -g
  - export NODE_ENV=development
  - knex migrate:latest --env development
  - knex seed:run
