# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
      - image: circleci/postgres:9.6.2-alpine
        environment:
        - POSTGRES_HOST=localhost
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=circle_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - name: Install Dependencies
        run: npm install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - name: Set up DB
        run: npm run knex:migrate && npm run knex:seed
        environment:
          POSTGRES_USER_LOCAL: ubuntu
          POSTGRES_DB_LOCAL: circle_test
          POSTGRES_HOST_LOCAL: "127.0.0.1"
      - name: Start the tests
        run: npm run test:server 