<template>
    <el-select v-model="selectedCountry"
               filterable
               :placeholder="placeholder"
               v-on:change="updateValue">
        <el-option
                v-for="item in countries"
                :key="item.numeric"
                :label="item.name"
                :value="item[optionValueAttr]">
        </el-option>
    </el-select>
</template>


<script>
    import Vue from 'vue'
    import { Select } from 'element-ui'

    Vue.use(Select)

    export default{
        props: {
            placeholder: {
                type: String,
                default: ''
            },

            // this allows using the `value` prop for a different purpose
            initValue: {
                type: String
            },

            valueType: {
                type: String // alpha2, alpha3, numeric, name
            }
        },

        created() {
            this.selectedCountry = this.initValue;
        },

        methods: {
            updateValue() {
                this.$emit('input', this.selectedCountry)
            }
        },

        computed: {
            optionValueAttr: function() {
                return (this.valueType && this.countries[0].hasOwnProperty(this.valueType) ? this.valueType : 'alpha2');
            }
        },

        data() {
            return {
                selectedCountry: null,
                countries: [
                    {name: "Afghanistan", alpha2: "AF", alpha3: "AFG", numeric: "004", name_lower: "afghanistan"},
                    {name: "Åland", alpha2: "AX", alpha3: "ALA", numeric: "248", name_lower: "åland"},
                    {name: "Albania", alpha2: "AL", alpha3: "ALB", numeric: "008", name_lower: "albania"},
                    {name: "Algeria", alpha2: "DZ", alpha3: "DZA", numeric: "012", name_lower: "algeria"},
                    {name: "American Samoa", alpha2: "AS", alpha3: "ASM", numeric: "016", name_lower: "american samoa"},
                    {name: "Andorra", alpha2: "AD", alpha3: "AND", numeric: "020", name_lower: "andorra"},
                    {name: "Angola", alpha2: "AO", alpha3: "AGO", numeric: "024", name_lower: "angola"},
                    {name: "Anguilla", alpha2: "AI", alpha3: "AIA", numeric: "660", name_lower: "anguilla"},
                    {name: "Antarctica", alpha2: "AQ", alpha3: "ATA", numeric: "010", name_lower: "antarctica"},
                    {name: "Antigua and Barbuda", alpha2: "AG", alpha3: "ATG", numeric: "028", name_lower: "antigua and barbuda"},
                    {name: "Argentina", alpha2: "AR", alpha3: "ARG", numeric: "032", name_lower: "argentina"},
                    {name: "Armenia", alpha2: "AM", alpha3: "ARM", numeric: "051", name_lower: "armenia"},
                    {name: "Aruba", alpha2: "AW", alpha3: "ABW", numeric: "533", name_lower: "aruba"},
                    {name: "Australia", alpha2: "AU", alpha3: "AUS", numeric: "036", name_lower: "australia"},
                    {name: "Austria", alpha2: "AT", alpha3: "AUT", numeric: "040", name_lower: "austria"},
                    {name: "Azerbaijan", alpha2: "AZ", alpha3: "AZE", numeric: "031", name_lower: "azerbaijan"},
                    {name: "Bahamas", alpha2: "BS", alpha3: "BHS", numeric: "044", name_lower: "bahamas"},
                    {name: "Bahrain", alpha2: "BH", alpha3: "BHR", numeric: "048", name_lower: "bahrain"},
                    {name: "Bangladesh", alpha2: "BD", alpha3: "BGD", numeric: "050", name_lower: "bangladesh"},
                    {name: "Barbados", alpha2: "BB", alpha3: "BRB", numeric: "052", name_lower: "barbados"},
                    {name: "Belarus", alpha2: "BY", alpha3: "BLR", numeric: "112", name_lower: "belarus"},
                    {name: "Belgium", alpha2: "BE", alpha3: "BEL", numeric: "056", name_lower: "belgium"},
                    {name: "Belize", alpha2: "BZ", alpha3: "BLZ", numeric: "084", name_lower: "belize"},
                    {name: "Benin", alpha2: "BJ", alpha3: "BEN", numeric: "204", name_lower: "benin"},
                    {name: "Bermuda", alpha2: "BM", alpha3: "BMU", numeric: "060", name_lower: "bermuda"},
                    {name: "Bhutan", alpha2: "BT", alpha3: "BTN", numeric: "064", name_lower: "bhutan"},
                    {name: "Bolivia", alpha2: "BO", alpha3: "BOL", numeric: "068", name_lower: "bolivia"},
                    {name: "Bonaire, Sint Eustatius and Saba", alpha2: "BQ", alpha3: "BES", numeric: "535", name_lower: "bonaire, sint eustatius and saba"},
                    {name: "Bosnia and Herzegovina", alpha2: "BA", alpha3: "BIH", numeric: "070", name_lower: "bosnia and herzegovina"},
                    {name: "Botswana", alpha2: "BW", alpha3: "BWA", numeric: "072", name_lower: "botswana"},
                    {name: "Bouvet Island", alpha2: "BV", alpha3: "BVT", numeric: "074", name_lower: "bouvet island"},
                    {name: "Brazil", alpha2: "BR", alpha3: "BRA", numeric: "076", name_lower: "brazil"},
                    {name: "British Indian Ocean Territory", alpha2: "IO", alpha3: "IOT", numeric: "086", name_lower: "british indian ocean territory"},
                    {name: "Brunei Darussalam", alpha2: "BN", alpha3: "BRN", numeric: "096", name_lower: "brunei darussalam"},
                    {name: "Bulgaria", alpha2: "BG", alpha3: "BGR", numeric: "100", name_lower: "bulgaria"},
                    {name: "Burkina Faso", alpha2: "BF", alpha3: "BFA", numeric: "854", name_lower: "burkina faso"},
                    {name: "Burundi", alpha2: "BI", alpha3: "BDI", numeric: "108", name_lower: "burundi"},
                    {name: "Cape Verde", alpha2: "CV", alpha3: "CPV", numeric: "132", name_lower: "cape verde"},
                    {name: "Cambodia", alpha2: "KH", alpha3: "KHM", numeric: "116", name_lower: "cambodia"},
                    {name: "Cameroon", alpha2: "CM", alpha3: "CMR", numeric: "120", name_lower: "cameroon"},
                    {name: "Canada", alpha2: "CA", alpha3: "CAN", numeric: "124", name_lower: "canada"},
                    {name: "Cayman Islands", alpha2: "KY", alpha3: "CYM", numeric: "136", name_lower: "cayman islands"},
                    {name: "Central African Republic", alpha2: "CF", alpha3: "CAF", numeric: "140", name_lower: "central african republic"},
                    {name: "Chad", alpha2: "TD", alpha3: "TCD", numeric: "148", name_lower: "chad"},
                    {name: "Chile", alpha2: "CL", alpha3: "CHL", numeric: "152", name_lower: "chile"},
                    {name: "China", alpha2: "CN", alpha3: "CHN", numeric: "156", name_lower: "china"},
                    {name: "Christmas Island", alpha2: "CX", alpha3: "CXR", numeric: "162", name_lower: "christmas island"},
                    {name: "Cocos (Keeling) Islands", alpha2: "CC", alpha3: "CCK", numeric: "166", name_lower: "cocos (keeling) islands"},
                    {name: "Colombia", alpha2: "CO", alpha3: "COL", numeric: "170", name_lower: "colombia"},
                    {name: "Comoros", alpha2: "KM", alpha3: "COM", numeric: "174", name_lower: "comoros"},
                    {name: "Congo (Brazzaville)", alpha2: "CG", alpha3: "COG", numeric: "178", name_lower: "congo (brazzaville)"},
                    {name: "Congo (Kinshasa)", alpha2: "CD", alpha3: "COD", numeric: "180", name_lower: "congo (kinshasa)"},
                    {name: "Cook Islands", alpha2: "CK", alpha3: "COK", numeric: "184", name_lower: "cook islands"},
                    {name: "Costa Rica", alpha2: "CR", alpha3: "CRI", numeric: "188", name_lower: "costa rica"},
                    {name: "Côte d'Ivoire", alpha2: "CI", alpha3: "CIV", numeric: "384", name_lower: "côte d'ivoire"},
                    {name: "Croatia", alpha2: "HR", alpha3: "HRV", numeric: "191", name_lower: "croatia"},
                    {name: "Cuba", alpha2: "CU", alpha3: "CUB", numeric: "192", name_lower: "cuba"},
                    {name: "Curaçao", alpha2: "CW", alpha3: "CUW", numeric: "531", name_lower: "curaçao"},
                    {name: "Cyprus", alpha2: "CY", alpha3: "CYP", numeric: "196", name_lower: "cyprus"},
                    {name: "Czech Republic", alpha2: "CZ", alpha3: "CZE", numeric: "203", name_lower: "czech republic"},
                    {name: "Denmark", alpha2: "DK", alpha3: "DNK", numeric: "208", name_lower: "denmark"},
                    {name: "Djibouti", alpha2: "DJ", alpha3: "DJI", numeric: "262", name_lower: "djibouti"},
                    {name: "Dominica", alpha2: "DM", alpha3: "DMA", numeric: "212", name_lower: "dominica"},
                    {name: "Dominican Republic", alpha2: "DO", alpha3: "DOM", numeric: "214", name_lower: "dominican republic"},
                    {name: "Ecuador", alpha2: "EC", alpha3: "ECU", numeric: "218", name_lower: "ecuador"},
                    {name: "Egypt", alpha2: "EG", alpha3: "EGY", numeric: "818", name_lower: "egypt"},
                    {name: "El Salvador", alpha2: "SV", alpha3: "SLV", numeric: "222", name_lower: "el salvador"},
                    {name: "Equatorial Guinea", alpha2: "GQ", alpha3: "GNQ", numeric: "226", name_lower: "equatorial guinea"},
                    {name: "Eritrea", alpha2: "ER", alpha3: "ERI", numeric: "232", name_lower: "eritrea"},
                    {name: "Estonia", alpha2: "EE", alpha3: "EST", numeric: "233", name_lower: "estonia"},
                    {name: "Ethiopia", alpha2: "ET", alpha3: "ETH", numeric: "231", name_lower: "ethiopia"},
                    {name: "Falkland Islands", alpha2: "FK", alpha3: "FLK", numeric: "238", name_lower: "falkland islands"},
                    {name: "Faroe Islands", alpha2: "FO", alpha3: "FRO", numeric: "234", name_lower: "faroe islands"},
                    {name: "Fiji", alpha2: "FJ", alpha3: "FJI", numeric: "242", name_lower: "fiji"},
                    {name: "Finland", alpha2: "FI", alpha3: "FIN", numeric: "246", name_lower: "finland"},
                    {name: "France", alpha2: "FR", alpha3: "FRA", numeric: "250", name_lower: "france"},
                    {name: "French Guiana", alpha2: "GF", alpha3: "GUF", numeric: "254", name_lower: "french guiana"},
                    {name: "French Polynesia", alpha2: "PF", alpha3: "PYF", numeric: "258", name_lower: "french polynesia"},
                    {name: "French Southern Lands", alpha2: "TF", alpha3: "ATF", numeric: "260", name_lower: "french southern lands"},
                    {name: "Gabon", alpha2: "GA", alpha3: "GAB", numeric: "266", name_lower: "gabon"},
                    {name: "Gambia", alpha2: "GM", alpha3: "GMB", numeric: "270", name_lower: "gambia"},
                    {name: "Georgia", alpha2: "GE", alpha3: "GEO", numeric: "268", name_lower: "georgia"},
                    {name: "Germany", alpha2: "DE", alpha3: "DEU", numeric: "276", name_lower: "germany"},
                    {name: "Ghana", alpha2: "GH", alpha3: "GHA", numeric: "288", name_lower: "ghana"},
                    {name: "Gibraltar", alpha2: "GI", alpha3: "GIB", numeric: "292", name_lower: "gibraltar"},
                    {name: "Greece", alpha2: "GR", alpha3: "GRC", numeric: "300", name_lower: "greece"},
                    {name: "Greenland", alpha2: "GL", alpha3: "GRL", numeric: "304", name_lower: "greenland"},
                    {name: "Grenada", alpha2: "GD", alpha3: "GRD", numeric: "308", name_lower: "grenada"},
                    {name: "Guadeloupe", alpha2: "GP", alpha3: "GLP", numeric: "312", name_lower: "guadeloupe"},
                    {name: "Guam", alpha2: "GU", alpha3: "GUM", numeric: "316", name_lower: "guam"},
                    {name: "Guatemala", alpha2: "GT", alpha3: "GTM", numeric: "320", name_lower: "guatemala"},
                    {name: "Guernsey", alpha2: "GG", alpha3: "GGY", numeric: "831", name_lower: "guernsey"},
                    {name: "Guinea", alpha2: "GN", alpha3: "GIN", numeric: "324", name_lower: "guinea"},
                    {name: "Guinea-Bissau", alpha2: "GW", alpha3: "GNB", numeric: "624", name_lower: "guinea-bissau"},
                    {name: "Guyana", alpha2: "GY", alpha3: "GUY", numeric: "328", name_lower: "guyana"},
                    {name: "Haiti", alpha2: "HT", alpha3: "HTI", numeric: "332", name_lower: "haiti"},
                    {name: "Heard and McDonald Islands", alpha2: "HM", alpha3: "HMD", numeric: "334", name_lower: "heard and mcdonald islands"},
                    {name: "Honduras", alpha2: "HN", alpha3: "HND", numeric: "340", name_lower: "honduras"},
                    {name: "Hong Kong", alpha2: "HK", alpha3: "HKG", numeric: "344", name_lower: "hong kong"},
                    {name: "Hungary", alpha2: "HU", alpha3: "HUN", numeric: "348", name_lower: "hungary"},
                    {name: "Iceland", alpha2: "IS", alpha3: "ISL", numeric: "352", name_lower: "iceland"},
                    {name: "India", alpha2: "IN", alpha3: "IND", numeric: "356", name_lower: "india"},
                    {name: "Indonesia", alpha2: "ID", alpha3: "IDN", numeric: "360", name_lower: "indonesia"},
                    {name: "Iran", alpha2: "IR", alpha3: "IRN", numeric: "364", name_lower: "iran"},
                    {name: "Iraq", alpha2: "IQ", alpha3: "IRQ", numeric: "368", name_lower: "iraq"},
                    {name: "Ireland", alpha2: "IE", alpha3: "IRL", numeric: "372", name_lower: "ireland"},
                    {name: "Isle of Man", alpha2: "IM", alpha3: "IMN", numeric: "833", name_lower: "isle of man"},
                    {name: "Israel", alpha2: "IL", alpha3: "ISR", numeric: "376", name_lower: "israel"},
                    {name: "Italy", alpha2: "IT", alpha3: "ITA", numeric: "380", name_lower: "italy"},
                    {name: "Jamaica", alpha2: "JM", alpha3: "JAM", numeric: "388", name_lower: "jamaica"},
                    {name: "Japan", alpha2: "JP", alpha3: "JPN", numeric: "392", name_lower: "japan"},
                    {name: "Jersey", alpha2: "JE", alpha3: "JEY", numeric: "832", name_lower: "jersey"},
                    {name: "Jordan", alpha2: "JO", alpha3: "JOR", numeric: "400", name_lower: "jordan"},
                    {name: "Kazakhstan", alpha2: "KZ", alpha3: "KAZ", numeric: "398", name_lower: "kazakhstan"},
                    {name: "Kenya", alpha2: "KE", alpha3: "KEN", numeric: "404", name_lower: "kenya"},
                    {name: "Kiribati", alpha2: "KI", alpha3: "KIR", numeric: "296", name_lower: "kiribati"},
                    {name: "Korea, North", alpha2: "KP", alpha3: "PRK", numeric: "408", name_lower: "korea, north"},
                    {name: "Korea, South", alpha2: "KR", alpha3: "KOR", numeric: "410", name_lower: "korea, south"},
                    {name: "Kuwait", alpha2: "KW", alpha3: "KWT", numeric: "414", name_lower: "kuwait"},
                    {name: "Kyrgyzstan", alpha2: "KG", alpha3: "KGZ", numeric: "417", name_lower: "kyrgyzstan"},
                    {name: "Laos", alpha2: "LA", alpha3: "LAO", numeric: "418", name_lower: "laos"},
                    {name: "Latvia", alpha2: "LV", alpha3: "LVA", numeric: "428", name_lower: "latvia"},
                    {name: "Lebanon", alpha2: "LB", alpha3: "LBN", numeric: "422", name_lower: "lebanon"},
                    {name: "Lesotho", alpha2: "LS", alpha3: "LSO", numeric: "426", name_lower: "lesotho"},
                    {name: "Liberia", alpha2: "LR", alpha3: "LBR", numeric: "430", name_lower: "liberia"},
                    {name: "Libya", alpha2: "LY", alpha3: "LBY", numeric: "434", name_lower: "libya"},
                    {name: "Liechtenstein", alpha2: "LI", alpha3: "LIE", numeric: "438", name_lower: "liechtenstein"},
                    {name: "Lithuania", alpha2: "LT", alpha3: "LTU", numeric: "440", name_lower: "lithuania"},
                    {name: "Luxembourg", alpha2: "LU", alpha3: "LUX", numeric: "442", name_lower: "luxembourg"},
                    {name: "Macao", alpha2: "MO", alpha3: "MAC", numeric: "446", name_lower: "macao"},
                    {name: "Macedonia", alpha2: "MK", alpha3: "MKD", numeric: "807", name_lower: "macedonia"},
                    {name: "Madagascar", alpha2: "MG", alpha3: "MDG", numeric: "450", name_lower: "madagascar"},
                    {name: "Malawi", alpha2: "MW", alpha3: "MWI", numeric: "454", name_lower: "malawi"},
                    {name: "Malaysia", alpha2: "MY", alpha3: "MYS", numeric: "458", name_lower: "malaysia"},
                    {name: "Maldives", alpha2: "MV", alpha3: "MDV", numeric: "462", name_lower: "maldives"},
                    {name: "Mali", alpha2: "ML", alpha3: "MLI", numeric: "466", name_lower: "mali"},
                    {name: "Malta", alpha2: "MT", alpha3: "MLT", numeric: "470", name_lower: "malta"},
                    {name: "Marshall Islands", alpha2: "MH", alpha3: "MHL", numeric: "584", name_lower: "marshall islands"},
                    {name: "Martinique", alpha2: "MQ", alpha3: "MTQ", numeric: "474", name_lower: "martinique"},
                    {name: "Mauritania", alpha2: "MR", alpha3: "MRT", numeric: "478", name_lower: "mauritania"},
                    {name: "Mauritius", alpha2: "MU", alpha3: "MUS", numeric: "480", name_lower: "mauritius"},
                    {name: "Mayotte", alpha2: "YT", alpha3: "MYT", numeric: "175", name_lower: "mayotte"},
                    {name: "Mexico", alpha2: "MX", alpha3: "MEX", numeric: "484", name_lower: "mexico"},
                    {name: "Micronesia", alpha2: "FM", alpha3: "FSM", numeric: "583", name_lower: "micronesia"},
                    {name: "Moldova", alpha2: "MD", alpha3: "MDA", numeric: "498", name_lower: "moldova"},
                    {name: "Monaco", alpha2: "MC", alpha3: "MCO", numeric: "492", name_lower: "monaco"},
                    {name: "Mongolia", alpha2: "MN", alpha3: "MNG", numeric: "496", name_lower: "mongolia"},
                    {name: "Montenegro", alpha2: "ME", alpha3: "MNE", numeric: "499", name_lower: "montenegro"},
                    {name: "Montserrat", alpha2: "MS", alpha3: "MSR", numeric: "500", name_lower: "montserrat"},
                    {name: "Morocco", alpha2: "MA", alpha3: "MAR", numeric: "504", name_lower: "morocco"},
                    {name: "Mozambique", alpha2: "MZ", alpha3: "MOZ", numeric: "508", name_lower: "mozambique"},
                    {name: "Myanmar", alpha2: "MM", alpha3: "MMR", numeric: "104", name_lower: "myanmar"},
                    {name: "Namibia", alpha2: "NA", alpha3: "NAM", numeric: "516", name_lower: "namibia"},
                    {name: "Nauru", alpha2: "NR", alpha3: "NRU", numeric: "520", name_lower: "nauru"},
                    {name: "Nepal", alpha2: "NP", alpha3: "NPL", numeric: "524", name_lower: "nepal"},
                    {name: "Netherlands", alpha2: "NL", alpha3: "NLD", numeric: "528", name_lower: "netherlands"},
                    {name: "Netherlands Antilles", alpha2: "AN", alpha3: "ANT", numeric: "530", name_lower: "netherlands antilles"},
                    {name: "New Caledonia", alpha2: "NC", alpha3: "NCL", numeric: "540", name_lower: "new caledonia"},
                    {name: "New Zealand", alpha2: "NZ", alpha3: "NZL", numeric: "554", name_lower: "new zealand"},
                    {name: "Nicaragua", alpha2: "NI", alpha3: "NIC", numeric: "558", name_lower: "nicaragua"},
                    {name: "Niger", alpha2: "NE", alpha3: "NER", numeric: "562", name_lower: "niger"},
                    {name: "Nigeria", alpha2: "NG", alpha3: "NGA", numeric: "566", name_lower: "nigeria"},
                    {name: "Niue", alpha2: "NU", alpha3: "NIU", numeric: "570", name_lower: "niue"},
                    {name: "Norfolk Island", alpha2: "NF", alpha3: "NFK", numeric: "574", name_lower: "norfolk island"},
                    {name: "Northern Mariana Islands", alpha2: "MP", alpha3: "MNP", numeric: "580", name_lower: "northern mariana islands"},
                    {name: "Norway", alpha2: "NO", alpha3: "NOR", numeric: "578", name_lower: "norway"},
                    {name: "Oman", alpha2: "OM", alpha3: "OMN", numeric: "512", name_lower: "oman"},
                    {name: "Pakistan", alpha2: "PK", alpha3: "PAK", numeric: "586", name_lower: "pakistan"},
                    {name: "Palau", alpha2: "PW", alpha3: "PLW", numeric: "585", name_lower: "palau"},
                    {name: "Palestine", alpha2: "PS", alpha3: "PSE", numeric: "275", name_lower: "palestine"},
                    {name: "Panama", alpha2: "PA", alpha3: "PAN", numeric: "591", name_lower: "panama"},
                    {name: "Papua New Guinea", alpha2: "PG", alpha3: "PNG", numeric: "598", name_lower: "papua new guinea"},
                    {name: "Paraguay", alpha2: "PY", alpha3: "PRY", numeric: "600", name_lower: "paraguay"},
                    {name: "Peru", alpha2: "PE", alpha3: "PER", numeric: "604", name_lower: "peru"},
                    {name: "Philippines", alpha2: "PH", alpha3: "PHL", numeric: "608", name_lower: "philippines"},
                    {name: "Pitcairn", alpha2: "PN", alpha3: "PCN", numeric: "612", name_lower: "pitcairn"},
                    {name: "Poland", alpha2: "PL", alpha3: "POL", numeric: "616", name_lower: "poland"},
                    {name: "Portugal", alpha2: "PT", alpha3: "PRT", numeric: "620", name_lower: "portugal"},
                    {name: "Puerto Rico", alpha2: "PR", alpha3: "PRI", numeric: "630", name_lower: "puerto rico"},
                    {name: "Qatar", alpha2: "QA", alpha3: "QAT", numeric: "634", name_lower: "qatar"},
                    {name: "Reunion", alpha2: "RE", alpha3: "REU", numeric: "638", name_lower: "reunion"},
                    {name: "Romania", alpha2: "RO", alpha3: "ROU", numeric: "642", name_lower: "romania"},
                    {name: "Russian Federation", alpha2: "RU", alpha3: "RUS", numeric: "643", name_lower: "russian federation"},
                    {name: "Rwanda", alpha2: "RW", alpha3: "RWA", numeric: "646", name_lower: "rwanda"},
                    {name: "Saint Barthélemy", alpha2: "BL", alpha3: "BLM", numeric: "652", name_lower: "saint barthélemy"},
                    {name: "Saint Helena", alpha2: "SH", alpha3: "SHN", numeric: "654", name_lower: "saint helena"},
                    {name: "Saint Kitts and Nevis", alpha2: "KN", alpha3: "KNA", numeric: "659", name_lower: "saint kitts and nevis"},
                    {name: "Saint Lucia", alpha2: "LC", alpha3: "LCA", numeric: "662", name_lower: "saint lucia"},
                    {name: "Saint Martin (French part)", alpha2: "MF", alpha3: "MAF", numeric: "663", name_lower: "saint martin (french part)"},
                    {name: "Saint Pierre and Miquelon", alpha2: "PM", alpha3: "SPM", numeric: "666", name_lower: "saint pierre and miquelon"},
                    {name: "Saint Vincent and the Grenadines", alpha2: "VC", alpha3: "VCT", numeric: "670", name_lower: "saint vincent and the grenadines"},
                    {name: "Samoa", alpha2: "WS", alpha3: "WSM", numeric: "882", name_lower: "samoa"},
                    {name: "San Marino", alpha2: "SM", alpha3: "SMR", numeric: "674", name_lower: "san marino"},
                    {name: "Sao Tome and Principe", alpha2: "ST", alpha3: "STP", numeric: "678", name_lower: "sao tome and principe"},
                    {name: "Saudi Arabia", alpha2: "SA", alpha3: "SAU", numeric: "682", name_lower: "saudi arabia"},
                    {name: "Senegal", alpha2: "SN", alpha3: "SEN", numeric: "686", name_lower: "senegal"},
                    {name: "Serbia", alpha2: "RS", alpha3: "SRB", numeric: "688", name_lower: "serbia"},
                    {name: "Seychelles", alpha2: "SC", alpha3: "SYC", numeric: "690", name_lower: "seychelles"},
                    {name: "Sierra Leone", alpha2: "SL", alpha3: "SLE", numeric: "694", name_lower: "sierra leone"},
                    {name: "Singapore", alpha2: "SG", alpha3: "SGP", numeric: "702", name_lower: "singapore"},
                    {name: "Sint Maarten (Dutch part)", alpha2: "SX", alpha3: "SXM", numeric: "534", name_lower: "sint maarten (dutch part)"},
                    {name: "Slovakia", alpha2: "SK", alpha3: "SVK", numeric: "703", name_lower: "slovakia"},
                    {name: "Slovenia", alpha2: "SI", alpha3: "SVN", numeric: "705", name_lower: "slovenia"},
                    {name: "Solomon Islands", alpha2: "SB", alpha3: "SLB", numeric: "090", name_lower: "solomon islands"},
                    {name: "Somalia", alpha2: "SO", alpha3: "SOM", numeric: "706", name_lower: "somalia"},
                    {name: "South Africa", alpha2: "ZA", alpha3: "ZAF", numeric: "710", name_lower: "south africa"},
                    {name: "South Georgia and South Sandwich Islands", alpha2: "GS", alpha3: "SGS", numeric: "239", name_lower: "south georgia and south sandwich islands"},
                    {name: "South Sudan", alpha2: "SS", alpha3: "SSD", numeric: "728", name_lower: "south sudan"},
                    {name: "Spain", alpha2: "ES", alpha3: "ESP", numeric: "724", name_lower: "spain"},
                    {name: "Sri Lanka", alpha2: "LK", alpha3: "LKA", numeric: "144", name_lower: "sri lanka"},
                    {name: "Sudan", alpha2: "SD", alpha3: "SDN", numeric: "729", name_lower: "sudan"},
                    {name: "Suriname", alpha2: "SR", alpha3: "SUR", numeric: "740", name_lower: "suriname"},
                    {name: "Svalbard and Jan Mayen Islands", alpha2: "SJ", alpha3: "SJM", numeric: "744", name_lower: "svalbard and jan mayen islands"},
                    {name: "Swaziland", alpha2: "SZ", alpha3: "SWZ", numeric: "748", name_lower: "swaziland"},
                    {name: "Sweden", alpha2: "SE", alpha3: "SWE", numeric: "752", name_lower: "sweden"},
                    {name: "Switzerland", alpha2: "CH", alpha3: "CHE", numeric: "756", name_lower: "switzerland"},
                    {name: "Syria", alpha2: "SY", alpha3: "SYR", numeric: "760", name_lower: "syria"},
                    {name: "Taiwan", alpha2: "TW", alpha3: "TWN", numeric: "158", name_lower: "taiwan"},
                    {name: "Tajikistan", alpha2: "TJ", alpha3: "TJK", numeric: "762", name_lower: "tajikistan"},
                    {name: "Tanzania", alpha2: "TZ", alpha3: "TZA", numeric: "834", name_lower: "tanzania"},
                    {name: "Thailand", alpha2: "TH", alpha3: "THA", numeric: "764", name_lower: "thailand"},
                    {name: "Timor-Leste", alpha2: "TL", alpha3: "TLS", numeric: "626", name_lower: "timor-leste"},
                    {name: "Togo", alpha2: "TG", alpha3: "TGO", numeric: "768", name_lower: "togo"},
                    {name: "Tokelau", alpha2: "TK", alpha3: "TKL", numeric: "772", name_lower: "tokelau"},
                    {name: "Tonga", alpha2: "TO", alpha3: "TON", numeric: "776", name_lower: "tonga"},
                    {name: "Trinidad and Tobago", alpha2: "TT", alpha3: "TTO", numeric: "780", name_lower: "trinidad and tobago"},
                    {name: "Tunisia", alpha2: "TN", alpha3: "TUN", numeric: "788", name_lower: "tunisia"},
                    {name: "Turkey", alpha2: "TR", alpha3: "TUR", numeric: "792", name_lower: "turkey"},
                    {name: "Turkmenistan", alpha2: "TM", alpha3: "TKM", numeric: "795", name_lower: "turkmenistan"},
                    {name: "Turks and Caicos Islands", alpha2: "TC", alpha3: "TCA", numeric: "796", name_lower: "turks and caicos islands"},
                    {name: "Tuvalu", alpha2: "TV", alpha3: "TUV", numeric: "798", name_lower: "tuvalu"},
                    {name: "Uganda", alpha2: "UG", alpha3: "UGA", numeric: "800", name_lower: "uganda"},
                    {name: "Ukraine", alpha2: "UA", alpha3: "UKR", numeric: "804", name_lower: "ukraine"},
                    {name: "United Arab Emirates", alpha2: "AE", alpha3: "ARE", numeric: "784", name_lower: "united arab emirates"},
                    {name: "United Kingdom", alpha2: "GB", alpha3: "GBR", numeric: "826", name_lower: "united kingdom"},
                    {name: "United States Minor Outlying Islands", alpha2: "UM", alpha3: "UMI", numeric: "581", name_lower: "united states minor outlying islands"},
                    {name: "United States of America", alpha2: "US", alpha3: "USA", numeric: "840", name_lower: "united states of america"},
                    {name: "Uruguay", alpha2: "UY", alpha3: "URY", numeric: "858", name_lower: "uruguay"},
                    {name: "Uzbekistan", alpha2: "UZ", alpha3: "UZB", numeric: "860", name_lower: "uzbekistan"},
                    {name: "Vanuatu", alpha2: "VU", alpha3: "VUT", numeric: "548", name_lower: "vanuatu"},
                    {name: "Vatican City", alpha2: "VA", alpha3: "VAT", numeric: "336", name_lower: "vatican city"},
                    {name: "Venezuela", alpha2: "VE", alpha3: "VEN", numeric: "862", name_lower: "venezuela"},
                    {name: "Vietnam", alpha2: "VN", alpha3: "VNM", numeric: "704", name_lower: "vietnam"},
                    {name: "Virgin Islands, British", alpha2: "VG", alpha3: "VGB", numeric: "092", name_lower: "virgin islands, british"},
                    {name: "Virgin Islands, U.S.", alpha2: "VI", alpha3: "VIR", numeric: "850", name_lower: "virgin islands, u.s."},
                    {name: "Wallis and Futuna Islands", alpha2: "WF", alpha3: "WLF", numeric: "876", name_lower: "wallis and futuna islands"},
                    {name: "Western Sahara", alpha2: "EH", alpha3: "ESH", numeric: "732", name_lower: "western sahara"},
                    {name: "Yemen", alpha2: "YE", alpha3: "YEM", numeric: "887", name_lower: "yemen"},
                    {name: "Zambia", alpha2: "ZM", alpha3: "ZMB", numeric: "894", name_lower: "zambia"},
                    {name: "Zimbabwe", alpha2: "ZW", alpha3: "ZWE", numeric: "716", name_lower: "zimbabwe"}
                ]
            }
        }
    }
</script>

<style>
</style>
